import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * Generates and downloads a professional PDF invoice for a maintenance record.
 * @param {Object} record - The maintenance record data.
 */
export const generateInvoicePDF = (record) => {
  const doc = new jsPDF();
  
  // Color Palette
  const colors = {
    primary: [37, 99, 235],    // #2563EB - Brand Blue
    secondary: [100, 116, 139], // #64748B - Slate
    dark: [15, 23, 42],        // #0F172A - Navy
    light: [241, 245, 249],     // #F1F5F9 - Gray
    success: [22, 163, 74]      // #16A34A - Green
  };

  // Helper: Clean amount for calculations
  const cleanAmount = (val) => {
    if (!val) return 0;
    return parseInt(String(val).replace(/[^0-9]/g, '')) || 0;
  };

  const baseAmount = cleanAmount(record.amount || record.cost);
  const platformFee = 150;
  const gst = Math.floor(baseAmount * 0.18);
  const totalAmount = baseAmount + platformFee + gst;

  // Header Section
  doc.setFontSize(26);
  doc.setTextColor(...colors.primary);
  doc.setFont("helvetica", "bold");
  doc.text("ORIGINODE", 105, 25, { align: "center" });
  
  doc.setFontSize(9);
  doc.setTextColor(...colors.secondary);
  doc.setFont("helvetica", "normal");
  doc.text("INDUSTRIAL NODE MAINTENANCE & SERVICE PORTAL", 105, 32, { align: "center" });
  
  // Top Line
  doc.setDrawColor(...colors.light);
  doc.setLineWidth(0.5);
  doc.line(20, 40, 190, 40);
  
  // Invoice Metadata
  doc.setFontSize(10);
  doc.setTextColor(...colors.secondary);
  doc.text("BILL TO:", 20, 55);
  doc.setTextColor(...colors.dark);
  doc.setFont("helvetica", "bold");
  doc.text("Authorized Industrial Operator", 20, 60);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...colors.secondary);
  doc.text("Enterprise Fleet Division", 20, 65);

  doc.text("INVOICE INFO:", 140, 55);
  doc.setTextColor(...colors.dark);
  doc.setFont("helvetica", "bold");
  doc.text(`ID: #INV-${record.id?.toString().substring(0, 8) || 'N/A'}`, 140, 60);
  doc.setFont("helvetica", "normal");
  doc.text(`Date: ${record.date || new Date().toLocaleDateString()}`, 140, 65);
  doc.setTextColor(...colors.success);
  doc.text(`Status: ${record.status || 'PAID'}`, 140, 70);

  // Table Data
  const tableRows = [
    ["Machine Identifier", record.machine || "Industrial Unit"],
    ["Service Classification", record.service || record.action || "General Maintenance"],
    ["Technical Specialist", record.expert?.replace(" (You)", "") || "Assigned Expert"],
    ["Base Service Cost", `INR ${baseAmount.toLocaleString()}`],
    ["Network Platform Fee", `INR ${platformFee.toLocaleString()}`],
    ["GST (Industrial Levy 18%)", `INR ${gst.toLocaleString()}`]
  ];

  autoTable(doc, {
    startY: 85,
    head: [["Service Item", "Description & Valuation"]],
    body: tableRows,
    theme: 'grid',
    headStyles: { 
      fillColor: colors.primary, 
      textColor: [255, 255, 255], 
      fontSize: 11,
      fontStyle: 'bold',
      halign: 'left'
    },
    bodyStyles: { 
      fontSize: 10, 
      cellPadding: 6,
      textColor: colors.dark 
    },
    columnStyles: { 
      0: { fontStyle: 'bold', width: 60, fillColor: [250, 250, 250] },
      1: { halign: 'right' }
    },
    margin: { left: 20, right: 20 }
  });

  // Final Summary
  const finalY = doc.lastAutoTable.finalY + 15;
  
  // Summary Box
  doc.setFillColor(...colors.light);
  doc.roundedRect(120, finalY, 70, 25, 3, 3, 'F');
  
  doc.setFontSize(10);
  doc.setTextColor(...colors.secondary);
  doc.setFont("helvetica", "bold");
  doc.text("TOTAL PAYABLE", 125, finalY + 10);
  
  doc.setFontSize(16);
  doc.setTextColor(...colors.primary);
  doc.text(`INR ${totalAmount.toLocaleString()}`, 125, finalY + 20);

  // Footer / Verification Section
  doc.setFontSize(8);
  doc.setTextColor(...colors.secondary);
  doc.setFont("helvetica", "normal");
  doc.text("DIGITALLY VERIFIED INVOICE", 105, 270, { align: "center" });
  doc.line(80, 272, 130, 272);
  
  doc.setFontSize(7);
  doc.text("This document is generated by the origiNode Industrial Maintenance Network.", 105, 278, { align: "center" });
  doc.text("All payments are secured via node-to-node encrypted protocols.", 105, 282, { align: "center" });
  
  // Download the PDF
  const fileName = `Invoice_#${record.id?.toString().substring(0, 6) || 'NA'}_${record.machine?.replace(/\s+/g, '_') || 'Unit'}.pdf`;
  doc.save(fileName);
};

