CREATE EXTENSION IF NOT EXISTS "pgcrypto";

ALTER TABLE producer_profiles ADD COLUMN IF NOT EXISTS points INTEGER NOT NULL DEFAULT 0;
ALTER TABLE producer_profiles ADD COLUMN IF NOT EXISTS level VARCHAR(20) NOT NULL DEFAULT 'Starter';
ALTER TABLE producer_profiles ADD COLUMN IF NOT EXISTS level_salary INTEGER NOT NULL DEFAULT 0;
ALTER TABLE producer_profiles ADD COLUMN IF NOT EXISTS last_active_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS overdue_penalty_applied BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS expert_point_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    expert_id UUID REFERENCES users(id) ON DELETE CASCADE,
    point_change INTEGER NOT NULL,
    reason TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
